name: Create Release

on:
  registry_package:
    types: [published]

jobs:
  release:
    if: ${{ startsWith(github.event.registry_package.package_version.version, 'v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_tag
        run: |
          echo "tag_name=${{ github.event.registry_package.package_version.version }}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          name: Release ${{ steps.get_tag.outputs.tag_name }}
          draft: false
          prerelease: false
          body: |
            This is a release for version ${{ steps.get_tag.outputs.tag_name }} of the NFS server Docker image.

            Changes:
            - NFS Server Docker image initial release
